### ISSUE TITLE
plugin does not work on jenkins 2.253

### ISSUE THREAD

**Issue by brunoballekens** [jenkinsci/google-compute-engine-plugin#200]
I have plugin version 4.3.0, but on jenkins 2.253 following exception is thrown when a new slave is launched :
```
2020-08-19 14:36:04.433+0000 [id=9284]  INFO    c.g.j.p.c.ComputeEngineComputerLauncher#launch: Launch will wait 300000 for operation operation-1597847762715-5ad3bec4d42a6-c6b1ed34-7a3a25be to complete...
2020-08-19 14:36:04.538+0000 [id=9284]  INFO    c.g.j.p.c.ComputeEngineCloud#lambda$getPlannedNodeFuture$0: Waiting 300000ms for node jenkins-dynamic-slave-2h0pik to connect
2020-08-19 14:36:10.799+0000 [id=47]    WARNING hudson.slaves.NodeProvisioner#lambda$update$6: Unexpected exception encountered while provisioning agent jenkins-dynamic-slave-2h0pik
java.lang.ClassNotFoundException: org.hamcrest.Matcher
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
        at org.awaitility.Awaitility.await(Awaitility.java:316)
        at org.awaitility.Awaitility.await(Awaitility.java:303)
        at com.google.cloud.graphite.platforms.plugin.client.ComputeClient.waitForOperationCompletion(ComputeClient.java:665)
        at com.google.jenkins.plugins.computeengine.ComputeEngineComputerLauncher.launch(ComputeEngineComputerLauncher.java:157)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:301)
Caused: java.util.concurrent.ExecutionException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.lambda$getPlannedNodeFuture$0(ComputeEngineCloud.java:315)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

issue probably introduced by https://issues.jenkins-ci.org/browse/JENKINS-63269

don't have this issue in version 2.252 (rolled back my jenkins instance to this version)

**Comment by Onager** [comment]
I ran into this too, rolling back the plugin version to 4.2.0 also worked on Jenkins 2.253

**Comment by donmccasland** [comment]
I've just released version 4.3.1 of the plugin which updates guava for security vuln and no longer pulls in hamcrest.  New image should be up on plugins.jenkins.io tomorrow.

**Comment by brunoballekens** [comment]
I just tried plugin version 4.3.1 with jenkins 2.253 and it still gives me the same exception.
The pulled in hamcrest does not come from guava, but via Awaitility....

**Comment by donmccasland** [comment]
Oh dang.  Okay.  Thanks for the feedback and the knowledge.  Let me see if
I can figure out how to get rid of hamcrest.

**Comment by brunoballekens** [comment]
well, if you need to get rid of hamcrest then you would need to get rid of awaitility ?
I lack very much knowledge on how plugins are instantiated on jenkins. But iff they can  package their own dependencies without impacting the system/other plugins, I would say you need to package hamcrest with the plugin ?

**Comment by francisdb** [comment]
```
mvn dependency:tree | grep hamcrest
[INFO] +- org.hamcrest:hamcrest-library:jar:2.2:test
[INFO] +- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |  \- org.hamcrest:hamcrest:jar:2.2:test
```

Looks like hamcrest is only available in test scope, I wonder why it's not being pulled in by the google graphite cloud client. I see that awaitility is already explicitly added in here so you will have to do the same for hamcrest. (remove test scope)
similar to https://github.com/jenkinsci/google-compute-engine-plugin/commit/b71c53b0b051dbbd63f6ed1796968fdc46b973b8

**Comment by francisdb** [comment]
Since you explicity put hamcrest in test scope it overrides the compile scope transitive dependency that comes from `com.google.cloud.graphite:gcp-client:jar:0.2.1:compile`

**Comment by donmccasland** [comment]
Oh that is an excellent clue to the necessary fix.

**Comment by shermanericts** [comment]
Sorry to bother, is there a 4.3.2 version of the plugin soon to be available?  I didn't see anything yet.

**Comment by shermanericts** [comment]
thanks!!

**Comment by donmccasland** [comment]
Thank you @jekkel !!

I've done a mvn release:prepare release:perform

Should take about a day for jenkins plugin site to update.

**Comment by francisdb** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/161305/91810934-07ff2080-ec2f-11ea-9108-2c8babb1bc4f.png">

```
...
Agent successfully connected and online
```

thanks
